Bangle.setOptions
({
  wakeOnBTN1: true,
  wakeOnFaceUp: false,
  wakeOnTwist: false,
  powerSave: true,
  lockTimeout: 10000,
  lcdPowerTimeout: 0,
  backlightTimeout: 10000,
  hrmPollInterval: 40,
});

Graphics.prototype.setFontNexaHeavy = function() {
  // Actual height 30 (29 - 0)
  // 1 BPP
  return this.setFontCustom(
    atob('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/+eAP/++AP/+/AP/+/AP/++AP/+eAMAAMAAAAAAAAAAAP+AAAP+AAAP+AAAP+AAAP+AAAP8AAAP+AAAP+AAAP+AAAP+AAAP+AAAAAAAAAAHgAAAHgAAcH+AA+H+AA//+AA//+AH//+AP//+AP//wAP//iAP+H+AP+P+AI//+AA//+AP//+AP//+AP//gAP//gAP+HgAP+DgAA+AAAAcAAAAAAAAAGAGAA/wPAB/4fAB/4fgD/8fgD/8Pgf/8Pw/5+P+/x+H+/w+H+/w+H+/w+P+Hw/P8D4//gD4f/gD8f/gB4P/ABwP+AAAD8AAAAAAAwAAAH8AAAH+AAAP+ACAP/AGAf/AeAePA+Af/D+AP/H+AP+f+AH8/4AD7/wAAP/AAAf8AAB/74AD/n8AP/P+AP8f+AP4f/APgePAPAf/AMAf+AIAP+AAAP8AAAH8AAAAgAAAAAAAAAAAAAH4AAQP8AD8f+AH//+AP//+AP///Af/8fAfP4fAfH8fAfP+fAf//fAP//+AP/f+AH+P8AH8/8ABw/+AAA/+AAA//AAAeeAAAAMAAAAAAAAAAAP+AAAP+AAAP+AAAP+AAAP+AAAAAAAAAA+AAAP/4AA//+AD///gH///wP///4f/j/8/4AP+/gAD+eAAA8MAAAYAAAAAMAAAQeAAA8/AAB+/wAH+f+A/8f///4P///wD///gB///AAf/8AAD/gAAAAAAAAAAABgAAAHsAAAH+AAAP+AAAP/AAAP+AAAP+AAAP/AAAD+AAAHsAAAHkAAAAgAAAAAAAAAAAAAAB4AAAB8AAAB8AAAB8AAAf/gAAf/wAAf/wAAf/wAAf/wAAf/wAAB8AAAB8AAAB8AAAB8AAAB4AAAAAAAAAAIAAAAeIAAA/4AAA/4AAA/4AAA/4AAAfgAAAMAAAAAAAAAAAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAAAAAAAAAAAAAeAAAA+AAAA/AAAA/AAAA/AAAA+AAAAMAAAAAAAAABwAAAPwAAA/wAAH/wAAf/wAD//gAf/+AB//4AP//AA//8AA//gAA/8AAA/wAAA+AAAA4AAAAAAAAAAAAAAAf/AAB//wAD//4AH//8AP//+AP//+AP4D+AfgA/AfgA/AfAAfAfAAfAfgA/AfwA/AP8H+AP//+AP//+AH//8AD//4AB//wAAf/AAAAAAAAAAAAD4AeAD4AeAH4AeAHwAeAH//+AP//+AP//+AP//+Af//+Af//+AAAAeAAAAeAAAAeAAAAAAAAD+AB4P+AD4f+AH4/+AP4/+AP5/+AP5/+APh8+Afh8+AfB4+AfB4+AfD4+Afn4+AP/4+AP/4+AP/w+AH/w+AD/g+AB/A+AAIAAAAAAAAAQDgAB4D4AD4D4AH4D8AP4D+AP5z+AP77+Afj4/AfD4fAfD4fAfD4fAfj4/AP/8/AP//+AP//+AH//+AH//8AD+f4AA8PwAAAAAAAAHAAAAfwAAA/wAAB/wAAD/wAAH/wAAP/wAAf/wAB/3wAD/nwAH+HwAP8HwAP//+AP//+AP//+AP//+AP//+AP//+AAAHwAAAHwAAAAAAAADAAP/z4AP/z8AP/z8AP/z+AP/z+AP/z+APnw/APnwfAPnwfAPnwfAPnw/APn//APn/+APj/+APj/8APh/8APA/4AAAfgAAAAAAAAAAAA//gAD//4AH//8AH//8AP//+AP//+APz9+Afnw/AfHwfAfHwfAfHwfAfnw/AP35+AP3/+APz/+APz/8AHx/8ADx/4AAwfwAAAAAAPgAAAPgACAPgAOAPgA+APgD+APgP+APg/+APj/+APv/+AP//4AP//gAP/+AAP/4AAP/gAAP+AAAP4AAAPgAAAAAAAAAAAAAA4PwAD+f4AH//8AH//+AP//+AP//+Af/8/AfD4/AfDwfAfDwfAfD4fAfj4/Af/9/AP//+AP//+AH//+AH//8AD+f4AA4PwAAAAAAAAAAAB/BwAD/x4AH/x8AH/5+AP/5+AP/9+Afz8/Afh8fAfB8fAfB8fAfB8fAfh8/AP//+AP//+AP//+AH//8AD//8AD//4AA//gAAAAAAAAAAAADweAAD4+AAH4/AAH4/AAD4/AAD4+AABgMAAAAAAAAgIAADweIAD4/4AH4/4AH4/4AD4/4ADwfgAAgMAAAAAAAAYAAAA8AAAB+AAAD/AAAH/gAAP/wAAf/4AA/v4AA/H4AAeDwAAMBgAAAAAAAHHAAAPngAAPngAAPngAAPngAAPngAAPngAAPngAAPngAAPngAAPngAAPngAAPngAAPngAAPngAAAAAAAAAAAAAAAAAMBgAAeDwAA/H4AA/v4AAf/4AAP/wAAH/gAAD/AAAB+AAAA8AAAAQAAAAAAAAAAAAB4AAAD4AAAH4AAAP4AAAP4AIAP4+eAPh++Afh+/AfD+/Afj++APn+eAP/4AAP/wAAP/gAAH/gAAD/AAAB+AAAAAAAAAACAAAB/4AAH/+AAP//gAf//wA///wA/wf4B/f38B8/78D5/98D7/8+Dz/++Dz/++Dzwe+Dzwe+Dz4++Dz/8+Dz/88D7/+8D7/+MB//+AB+AeAA//+AA//+AAf/8AAP/8AAD/4AAA/gAAAAAAAAAeAAAB+AAAP+AAA/+AAD/+AAP/+AB//4AH//wAP//wAP/nwAP+HwAP4HwAP+HwAP/3wAP//wAH//wAB//4AAP/+AAD/+AAA/+AAAP+AAAB+AAAAeAAAAGAAAAAAAAAAAAAAAAP//+AP//+AP//+AP//+AP//+AP//+APD4+APD4+APD4+APD4+APD4+APj4+AP/4+AP//+AP//+AH//+AH//8AD+f4AB8P4AAADAAAAAAAABwAAAf/AAA//gAB//4AD//4AH//8AP//+AP8H+APwB+AfgA/AfgA/AfAAfAfAAfAfAAfAfgA/AfgA/APwB+APwB+AHwB+AHgA8ADAAYAAAAAAAAAAAAAAAAP//+AP//+AP//+AP//+AP//+AP//+APgA+APgA+APgA+APgA+APgA+APgA+APwB+AP8D+AH//8AH//8AD//4AB//wAA//gAAf/AAAD4AAAAAAAAAAAAAAAAAP//+AP//+AP//+AP//+AP//+AP//+APj4+APj4+APj4+APj4+APj4+APj4+APj4+APj4+APj4+APj4+APjw+AAAAeAAAAAAAAAAAAAAAAP//+AP//+AP//+AP//+AP//+AP//+APh8AAPh8AAPh8AAPh8AAPh8AAPh8AAPh8AAPh8AAPh8AAPh8AAPAAAAAAAAAABwAAAf/AAA//gAB//4AD//4AH//8AP//+AP4D+APwB+AfgA/AfgAfAfD4fAfD4fAfD4fAfD4fAfj4/APz/+APz/+APz/+AHj/8ADD/4AAD/4AAAAAAAAAAAAAAAAP//+AP//+AP//+AP//+AP//+AP//+AAD4AAAD4AAAD4AAAD4AAAD4AAAD4AAAD4AAP//+AP//+AP//+AP//+AP//+AP//+AP//+AAAAAAAAAAAAAAAAP//+AP//+AP//+AP//+AP//+AP//+AAAAAAAAPAAAAPwAAAP4AAAP8AAAP+AAAP+AAAH+APAA/APgA/APgAfAPgAfAPgA/APgA/APgD+AP//+AP//+AP//8AP//4AP//wAP//AAAAAAAAAAAAAAAAAP//+AP//+AP//+AP//+AP//+AP//+AAP+AAAf/AAB//gAD//wAH//8AP+P+AP8H+AP4D+APgB+APAA+AOAAeAMAAOAIAAGAAAAAAAAAAAAAAAAP//+AP//+AP//+AP//+AP//+AP//+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAAAAAAAAAAAAAAP//+AP//+AP//+AP//+AP//+AP//+AH/AAAD/wAAB/4AAAf8AAAP+AAAH/AAAH/AAAP+AAAf8AAB/4AAD/wAAH/AAAP//+AP//+AP//+AP//+AP//+AP//+AP//+AAAAAAAAAAAAAAAAP//+AP//+AP//+AP//+AP//+AP//+AH//+AD/wAAB/4AAAf+AAAP/AAAH/gAAB/4AAA/8AP//+AP//+AP//+AP//+AP//+AP//+AAAAAAABwAAAf/AAA//gAD//4AD//4AH//8AP//+AP8H+APwB+AfgA/AfgA/AfAAfAfAAfAfAAfAfgA/AfgA/APwB+AP4D+AP//+AH//8AD//4AD//4AB//wAAf/AAAD4AAAAAAAAAAAAAAAAAP//+AP//+AP//+AP//+AP//+AP//+APg+AAPg+AAPg+AAPg+AAPg+AAPg+AAPx+AAP/+AAP/+AAH/8AAH/8AAD/4AAA/gAAAAAAAABwAAAf/AAA//gAD//4AD//4AH//8AP//+AP8H+APwB+AfgA/AfgA/AfAAfAfAAfAfAAfAfgA/AfgA/APwB+AP4D+AP//+AH///AD///gD///gB///gAf/PAAD4GAAAAAAAAAAAAAAAAP//+AP//+AP//+AP//+AP//+AP//+APg8AAPg8AAPg/AAPg/gAPg/wAPh/8AP//+AP//+AP//+AH/5+AH/4+AD/wOAA/AGAAAACAAAAAAAYAYAD/A8AH/h8AH/h+AP/x+AP/w+Af/w/Afn4/AfH4fAfD4fAfD4fAfD4/AfD8/APj/+APh/+APx/+AHg/8AHA/4AAAPwAAAAAAPgAAAPgAAAPgAAAPgAAAPgAAAPgAAAP//+AP//+AP//+AP//+AP//+AP//+APgAAAPgAAAPgAAAPgAAAPgAAAPgAAAPAAAAAAAAAAAAAAAAAAAP//gAP//wAP//4AP//8AP//+AP//+AAAD+AAAA/AAAA/AAAAfAAAAfAAAA/AAAA/AAAD+AP//+AP//+AP//8AP//4AP//wAP//AAAAAAAMAAAAPgAAAP4AAAP/AAAP/wAAP/+AAP//gAD//4AAf/+AAH/+AAA/+AAAH+AAAf+AAD/+AAf/+AB//8AP//gAP/+AAP/4AAP/AAAP8AAAPgAAAAAAAAOAAAAPwAAAP+AAAP/wAAP/8AAP//gAP//8AB//+AAP/+AAA/+AAA/+AAH/+AA//+AH//8AP//gAP/8AAP/gAAP/4AAP//AAH//4AA//+AAH/+AAA/+AAAf+AAH/+AA//+AH//+AP//wAP/+AAP/wAAP+AAAP4AAAPAAAAAAAAAMAAGAOAAeAPgA+APwD+AP8H+AP+f+AP//+AH//8AD//wAA//gAAf/AAA//gAD//4AP//8AP//+AP+P+AP4H+APwB+APAA+AOAAOAIAAGAAAAAAMAAAAOAAAAPgAAAPwAAAP8AAAP+AAAP/gAAH/wAAB//+AA//+AAP/+AAP/+AA//+AB//+AH/4AAP/gAAP/AAAP8AAAP4AAAPgAAAPAAAAAAAAAPAAOAPgAeAPgB+APgD+APgP+APgf+APh/+APj/+APv/+AP/++AP/8+AP/w+AP/g+AP+A+AP8A+APwA+APgA+AOAA+AMAAeAAAAAAAAAAAP///8f///8f///8f///8f///8f///8fAAA8fAAA8fAAA8PAAA8AAAAAwAAAA+AAAA/gAAA/8AAA//AAA//4AAP/+AAD//wAAf/+AAH//gAA//wAAH/wAAB/wAAAPwAAADwAAAAAAAAAAfAAA8fAAA8fAAA8f///8f///8f///8f///8f///8f///8AAAAAAAgAAADgAAAHgAAAfgAAA/gAAD/gAAP/AAAP+AAAP4AAAP4AAAP8AAAP/AAAD/gAAB/gAAAfgAAAPgAAADgAAABgAAAAAAAAAAA4AAAB4AAAB4AAAB4AAAB4AAAB4AAAB4AAAB4AAAB4AAAB4AAAB4AAAB4AAAB4AAAB4AAAB4AAAB4AAAAAPgAAAPgAAAPgAAADgAAAAAAAAAAfAAAB/wAAD/4AAH/8AAP/+AAP/+AAP//AAPg/AAfAfAAPAfAAPgeAAPw+AAP/+AAP/+AAP/+AAP/+AAP/+AAP/+AAAAAAAAAAAP//+AP//+AP//+AP//+AP//+AP//+AAPw+AAPgeAAPAfAAfAfAAPg/AAP//AAP/+AAP/+AAH/8AAD/4AAB/wAAAOAAAAAAAAA/gAAD/4AAD/8AAH/8AAP/+AAP/+AAPx/AAPg/AAfAfAAfAfAAPg/AAPg+AAPg+AAHAeAAGAMAAAAAAAAfAAAB/wAAD/4AAH/8AAP/+AAP/+AAP//AAPg/AAfAfAAPAfAAPgeAAPw+AP//+AP//+AP//+AP//+AP//+AP//+AAAAAAAA/gAAD/4AAH/8AAH/8AAP/+AAP/+AAPu/AAfOfAAfOfAAfOfAAPufAAP+fAAP++AAH++AAH+cAAD+MAAA+AAAAAAAAPAAAAPAAAAPAAAB//+AH//+AP//+AP//+Af//+Af//+AfvAAAfPAAAfPAAAAAAAAAAAAAAD+DwAP/D8Af/j8Af/z+A//z+A//7/A+H4/B8D4fB8D4fB8D4fA+H8/A////B///+D///+D///8B//f8A7+P4AAAAAAAAAAP//+AP//+AP//+AP//+AP//+AP//+AAPgAAAPAAAAPAAAAfgAAAP/+AAP/+AAP/+AAP/+AAH/+AAB/+AAAP+AAAAAAAAAAAPP/+APv/+Afv/+Afv/+Afv/+APP/+AGAAAAAAAAAAAAAeef///ff//+/f//+/f//+/f//8ef//4MAAAAAAAAAAAAAAP//+AP//+AP//+AP//+AP//+AP//+AAB/wAAH/4AAP/+AAP/+AAP7+AAPh+AAPA+AAOAeAAIAGAAAACAAAAAAAAAAAP//+AP//+AP//+AP//+AP//+AP//+AAAAAAAAAAAAP/+AAP/+AAP/+AAP/+AAP/+AAP/+AAPgAAAPAAAAfAAAAf/+AAP/+AAP/+AAP/+AAH/+AAP/+AAP/+AAPgAAAfAAAAfgAAAP/+AAP/+AAP/+AAP/+AAH/+AAD/+AAAAAAAAAAAAP/+AAP/+AAP/+AAP/+AAP/+AAP/+AAPgAAAPAAAAPAAAAfgAAAP/+AAP/+AAP/+AAP/+AAH/+AAB/+AAAP+AAAAAAAAAAAAA/gAAD/4AAH/8AAH/+AAP/+AAP/+AAPw/AAfgfAAfAfAAfAfAAPg/AAP/+AAP/+AAH/+AAH/8AAD/4AAB/wAAAAAAAAAAAAP///AP///AP///AP///AP///AP///APw+AAPgeAAPAfAAfAfAAPg/AAP//AAP/+AAP/+AAH/8AAD/4AAB/wAAAOAAAAAAAAAfAAAB/wAAD/8AAH/8AAP/+AAP/+AAP//AAPg/AAfAfAAPAfAAPgeAAPw+AAP///AP///AP///AP///AP///AP///AAAAAAAAAAAP/+AAP/+AAP/+AAP/+AAP/+AAP/+AAPwAAAPgAAAfAAAAfgAAAPgAAAPgAAAOAAAAAAAAAAAAAAD4cAAH8+AAH++AAP++AAP+fAAP/fAAfffAAfffAAff/AAPP/AAPv+AAPv+AAPn8AAGH8AAAAAAAPAAAAPAAAD//wAD//8AD//+AD//+AD///AD///AAPA/AAPAfAAPAeAAPAeAAAAGAAAAAAAH/AAAP/4AAP/8AAP/+AAP/+AAP//AAP//AAAA/AAAAfAAAAeAAAB+AAP/+AAP/+AAP/+AAP/+AAP/+AAP/+AAAAAAAMAAAAPAAAAP4AAAP+AAAP/gAAP/8AAP/+AAB/+AAAf+AAAH+AAA/+AAD/+AAP/+AAP/4AAP/AAAP8AAAPwAAAAAAAAPAAAAP4AAAP/AAAP/4AAP/+AAP/+AAD/+AAAP+AAA/+AAD/+AAP/+AAP/wAAP+AAAP/wAAP/+AAD/+AAAf+AAAP+AAD/+AAP/+AAP/+AAP/4AAP/AAAP4AAAPAAAAAAAAAIAGAAOAOAAPg+AAPx+AAP/+AAP/+AAP/+AAH/4AAB/wAAH/8AAP/+AAP/+AAP/+AAPx+AAPAeAAOAOAAAAAAAOAAAAPwAAAP8AAAP/gHAP/4/AP///AH///AA///AAH//AAf/8AD//wAP//AAP/4AAP/gAAP+AAAPwAAAPAAAAAAAAAAAGAAPAOAAPg+AAPh+AAPn+AAPv+AAP/+AAP/+AAP/+AAP/+AAP8+AAP4+AAPw+AAPA+AAOA+AAAAAAAAcAAAA+AAA//+AH///wP///4P///8f///8f/3/8f/B/8fAAA8fAAA8AAAAAAAAAAAAAAA////w////w////w////w////w////wAAAAAOAAA4fAAA8fAAA8f/A/8f/3/8f///8P///8P///4H///wB///AAA+AAAAAAAAAAAAAAcAAAA8AAAB8AAAB+AAAB8AAAB4AAAB8AAAB8AAAB+AAAA+AAAA+AAAA+AAAB+AAAB+AAAA8AAAA8AAAAwAAAAAAAA='),
    32,
    atob("BwoNFxQbFgcMDA4RCQ8JEBYPFRQVFBUSFRUJCQwQDhMdGRcWGBUUFxcJFRYTHBcaFhoXFBQXFyIWFhQMEAsTEQUTFBATEg0TEwkJEggbExMUEw8QDhISGhESEAwJDBM="),
    30|65536
  );
};



E.setTimeZone(-5);

function mainWindow() 
{

  let d = new Date();
  let h = d.getHours();
  let m = d.getMinutes();

  let dayMonth = d.getDate();
  let dayWeek = d.getDay();
  let month = d.getMonth();
  month +=1;
  let year = d.getFullYear();

  let steps = Bangle.getStepCount();

  let battery = E.getBattery();

  switch (dayWeek)
  {
    case 0:
      dayWeek = "Sun";
      break;
    case 1:
      dayWeek = "Mon";
      break;
    case 2:
      dayWeek = "Tues";
      break;
    case 3:
      dayWeek = "Wed";
      break;
    case 4:
      dayWeek = "Thur";
      break;
    case 5:
      dayWeek = "Fri";
      break;
    case 6:
      dayWeek = "Sat";
  }

  stepsIcon = require("heatshrink").decompress(atob("AAOBgP/AA/AgE/BZAAy+BNCH/aNDg4+5/DOEH/L9BAAcfX3gABgY+3/g/FYHHwH4zA3fwoABg7+8AAMBf3oABv4/0/A/In4/0+A/Ih4/04A/IgY/0wA/IgI/0HxAABv4+y/g/Kj4/y/A/Kh4/y+A/Kg4/y8A/KgI/y4A/KgA/ywA/Lv4/xHxcAj4+w/w/Mh4/w/g/Mg4/+gY/w/A/MgI/w+A/MgF/H9/gH5s/H9/AH5sfH/0PH9+AH5sHH94+NgEDH/0BH13+H50AH938H59/H/0/H9v4H58fH9vwH58PH/0HH9vgH/4/PgY/t4A/PgI/+gA/twA/Qv4/+n4/sHyEAj4//H1f+H6MPH/0HH9f8H6MDH/0BH9f4H/4/RgA/r+A/Sv4//H/0/H9XgH6UfH/0PH/7yfgYMJ4A/Sg4+c/hhMH6ZeKACQxEH/P+EQkfBw+AH6UBfrpiMH6adJACQwGH+6+FYBI+TgF/H7P4EQ0HH7c/H7PgEQ0DH+zvIZxoANbg7+ZMY4/Vh7+gMY4/vfw4ABg4/aDYoAT4AjIgYPE/g/uEhQ/aLYoASVxd/H7MBH6/4EhU/H+XwEhUfKB7bPACXAEZUPH+WAEZUHH7V/H6wjLgY/x/gjLgIRD+A/Vn4/VNpo/xFpqkDH60fH6vgMiA/Wh4/V4BkQH9uAEiCRNABEHHyn+EiI/s/g/ogY/U/AkRH9nwEhsBH7IaDACIsPH9/AH6ISPDRQARwAkOv4/uEh8/H7JaCACH+H/38Eh8fH9v4H9SaCACHwEh8PH/0HH7KaCACHgH6WAH9RrQgY/ZbQQAQFaA/uEiEBH7LaCAB/+H/38EqI//H7MDH6P4EqN/H9fwH9cBH6PgEqM/H/4/YgA/R4AkRj4/rFSQ/BHy4/SEiQ/av4/jh4/q/w/tn4/P/gkSg4/q/A//H9sfH5/wEiUDH9XgH/4/th4/P4AkSgI/qwA//H9sHH54lUH9P+H/4/ugY/O/glUv4/o/A//H90BH53wH/4lUn4/o8A/ugA/O4A//H/2AEikfH7N/H/4/NEisfKyo//AAc/Hxn+EisPH8/8H/4/+/A/wj4//H5nwEisHH/4/n8A/wh4//H5nAH/4/wg4/ME6w//gaXWH6AkWH/4/n/w/xgY//H5f8H/4//H+MBH5f4Ei/gH/4/l+A//H/wmXH7UAH/4//H5fAH6/wH/4/lwA/yv4//H5QjXH/4//gH4H8n+H/4/zn4/J/g//H/4/+ErJZZH/4//gEfH5PwH/4//EjH+H8ngH/4//H/3AEjH/H/4/Zh4//H5OAH/4/ZDTI//H5SkZH/4////AH8X+H/4jYgI//H7UHH5H8H7XgH/4//H/4/i/A/a+A//H/4/iEbI/BLbI//H/4/l/g//H8XgEbEDH/4////+H/4/i4A//H7X/H/4//H8WAEbYcYH/4/mbjA//H/4/JHzAjD8A//H/4/7h4cB+A//H8H+H/4/c/A//H/38H/cfH/4/jELA/ELrA//H83/H/c/H7UPH82AH/4/f/A//H7vAH/V/H/4eC8A//H/3wH/4bWj4/iDzY//H5CgXH438H/4/5gIeD/w//H/3/Di0/H/4/hgYfEwA//H/3AH/4/4g4fE8AcVv4/HD6w//H5CfWH/4/ih4fE/AcVHw4//H8H8H/EfD4n+H/4bUgI/o/4/4n4//EAuADacDH9PADacHH/4/iv4gah4/+j4/iEA3wLbQ/j/AaSgI+IH+sHH8RjH/i+cH8P+DSMDHxI/0n4/jMhB+cH8WAPzY/ybA4/eg4hH4AYOj4/uEJx+NH8XwC5sPH8wnIH5w+NH8X4PzY/Zj4hH/h+bH8X+CpcHH/1/H9E/ERB+bH8eAPzQ/ZFRPACZEDHyH/+A/rSZI/rURB+SH7IiSj4/1/ARGgI+SH7AsK/h+aH8f+PzQ/YgYjKCIsPH/w+UH8mAPzI/Yg4jK4B+Z//4H8XgB5w/jVxajDv4/6EYR+XH7EfEZX+PzI/k/+AgY+XH7E/Ehh+O/kBH9oAP4DPJ/g/WeDAzFbxA/zPwMAg4/fHzX+DwUDH/XgDwUBH7wfIPyo/7PwafJJogARb5AAREAt/H+/wH8kHPzw/4Pw0An5POAB0PH6+AH8sfHy34EA4/2Pw4gJH6peIABv8MCI/s4A/RSJAAMv5+eH+p+JgEPCaQAKHyn+EBQ/dgI/U8A/TChY/dPxY/J+A/TgY/TFJkHCo/4H9AhMH5H8H6YdIPy4hJapjdQPy6hKwA/lc5w/J8A/Sj4/RMxw/JYCc/Pz4/KQCY/Rcp8BDRP8H6N/Hx6kQH5X/4A/QX0A/MQCI/Q+A/bbjYAG8BicTp8DH6DieQB0HH6ChPH5yAOH+H/DZsPH6A+QgF/D5nwDZkfH+AgNH6H+H8CAMn4/iEZwhMLZw/j//gDZT+Q/g/hMRUBH+aAKH8kfEbMDH+n/4AaHg4/1EhEPH+v/wAaY/w/RMiP//AaGn4/2QA4/4QA1/H+//DQoYYABcHH6fwDIcBH/InEgY/68AZWH8/+DIUPC6WAH6ClTQAsfH/aACv4/7//AgIVUH7GAn6AOfyY/ZV4KIXH8v4BIKAOH9vwZJIAb8A/XDAd/H+cBTBMHH/WABYaAhH7ALEQEPwH7kAH/H+BgsPH/yAg/A/W/gNGQD4/fBoo/5gEfH98DH5qAeE5A/OK5KAdH8IPFH/MAn4/+QDn+H63wCJSAbH8cHH/0Av4/+QDY/QFgvgCZg//h4/+QDWAH6vAChqAZH6AqFH50BH/0Aj4/+QDAoPH4xWQv4/nVIo/QYC4/nSwoAR8A/mg4/nn4WECp8AgY/+gI/W+A/mgA/nv4VD/w/o/A/nC4g/iCog//H9P8Ex0BCqgACn4//H6qpPgY//H93/Ex0HCgn4H9OAH/4mNh4/v4AmNj4/v8A/T+A/Rv4/lMwo/qFRwmFH9TqOH/7UUDBIAR/glMgI/w/wlMgY/w/4/lTAwASwAmLg4/x4AmLh4TSH9cfH+KrMn4/XgY/Y+AmLv4/x/AmLaaY/e/zlSH9f/EqQ/Rg4/ZwAlJh4/zFhUfH+fwEpM/H+f4EpKSSbJwAS/gkIgI/0/4kIgY/1wAkQH6MfH7XgEg8/H+v4Eg4RIH9v+fx4/u/+Afxw/SbRAAT8AjPH938EQkBCBI/uYAq+JH+HwEQd/H7YcKQC0HBxXgH9/+gEDBxY/wABw//H6I+sH///+A//Hx8BH/4//H9v4H/4/PgY//H9v8H/4/Pg4//H9v+H/4/Ph4/t/4//H58fH/4/uwA/On4//H93AH51/H/4/u8A/OH13/+A//HxsBH9/4H5sDH/4/v/g/Ng4/v/w/Nh4/v/4//H5sfH+GAH5k/H+HAH5l/H+HgH/3wH5g+wH5sBH+P4H5cDH+P8H5cHH+P+H5cPH+P/H5cfH+XAH5U/H+XgH5V/H+XwHxMBH2X//A/JgY/z/g/Jg4/z/4/Jh4/0wA/In4/08A/Iv4/0+A+HgI+0//8H48HH+v/H48PH+3AH40/H+3wf3gAB/j+9AAOAH4kfH/DAFH3H//w+Dh4/5//gP3gACwEAn4VS"));


  let am = h < 12;
  h = h % 12;
  if(h == 0) h = 12;

  g.clear();
  g.setFont("NexaHeavy");
  g.setFontAlign(0,0,0);
  g.drawString(h + ":" + String(m).padStart(2, "0") + " " + (am?"AM":"PM"), 176/2, (176/2)-20);

  g.setFont("12x20");
  g.drawString(dayWeek + " " + month + "/" + dayMonth, 176/2, (176/2)+15);

  g.setFontAlign(1,0,0);
  g.drawString(steps, 176-2, 12);

  g.setFont("12x20");
  g.setFontAlign(-1,0,0);
  g.drawString(battery + "%", 4, 12);

  
  g.drawImage(stepsIcon, 176/2, 150);


}

function topWindow()
{
  g.clear();
}

function bottomWindow()
{
  g.clear();
}

function leftWindow()
{
  g.clear();
}

function rightWindow()
{
  g.clear();
}

let windowFunction = mainWindow;


function changeWindow()
{
  if(win == windowFunction) return;
  windowFunction = win;
  windowFunction();
}

function main()
{
  windowFunction();
}

Bangle.on("swipe", function(lr, ud)
{
  if(windowFunction == mainWindow && ud == 1)
    {
      changeWindow(topWindow);
    } else if(windowFunction == topWindow && ud == -1)
    {
      changeWindow(mainWindow);
    } else if (windowFunction == mainWindow && ud == -1)
    {
      changeWindow(bottomWindow);
    } else if(windowFunction == bottomWindow && ud == 1)
    {
      changeWindow(mainWindow);
    } else if(windowFunction == mainWindow && lr == 1)
    {
      changeWindow(leftWindow);
    } else if(windowFunction == leftWindow && lr == -1)
    {
      changeWindow(mainWindow);
    } else if(windowFunction == mainWindow && lr == -1)
    {
      changeWindow(rightWindow);
    } else if(windowFunction == rightWindow && lr == 1)
    {
      changeWindow(mainWindow);
    }
});

setInterval(main,60000);
main();